version: "3.9"
services:
  db:
    container_name: db-certamen2usm
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: certamen2usm_db
      MYSQL_USER: zgames
      MYSQL_PASSWORD: 123456
    networks:
      - net-certamen2usm
  web:
    container_name: web-certamen2usm
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - "./web:/var/www/html"
      - "./httpd.conf:/etc/httpd/conf/httpd.conf"
    image: laravel-php8
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - net-certamen2usm
networks:
  net-certamen2usm:
    
